Import PyTorch

PyTorch is a deep learning and tensor computation library. It provides tensors, automatic differentiation, GPU acceleration, and neural network tools.



In [ ]:
import torch

Create Random Tensor

A tensor is a multidimensional array similar to NumPy arrays. Random tensors are often used to initialize neural network weights.

In [ ]:
torch.rand(2,4)

tensor([[0.8757, 0.5305, 0.3706, 0.6255],
        [0.4399, 0.7000, 0.3540, 0.3317]])

Scalar Tensor

A scalar is a single numerical value represented as a 0-dimensional tensor.

In [ ]:
scalar = torch.tensor(7)
print(scalar)
print(f"Dimension of scalar: {scalar.ndim}")
print(f"Shape of scalar: {scalar.shape}")

tensor(7)
Dimension of scalar: 0
Shape of scalar: torch.Size([])


Vector Tensor

A vector is a 1-dimensional tensor containing multiple values in a single direction.

In [ ]:
vec = torch.tensor([1,2,3,4])
print(vec)
print(f"Dimension of vec: {vec.ndim}")
print(f"Shape of vec: {vec.shape}")

tensor([1, 2, 3, 4])
Dimension of vec: 1
Shape of vec: torch.Size([4])


3D Tensor

A tensor can have multiple dimensions. Higher-dimensional tensors are widely used in deep learning.

In [ ]:
ten = torch.tensor([[[1,2,3],
                     [4,5,6],
                     [7,8,9]]])
print(f"Dimension of ten: {ten.ndim}")
print(f"Shape of ten: {ten.shape}")

Dimension of ten: 3
Shape of ten: torch.Size([1, 3, 3])


Display Tensor

Printing a tensor helps visualize its contents.

In [ ]:
ten

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
rand = torch.rand(3,4)
zeros = torch.zeros(3,4)
ones = torch.ones(3,4)
eye = torch.eye(3)
arange = torch.arange(start=0, end=10, step=2)
linspace = torch.linspace(start=0, end=10, steps=5)

Tensor Initialization Methods

PyTorch provides various functions to create tensors efficiently.

In [ ]:
print(f"rand: {rand}")
print(f"zeros: {zeros}")
print(f"ones: {ones}")
print(f"eye: {eye}")
print(f"arange: {arange}")
print(f"linspace: {linspace}")

rand: tensor([[0.7073, 0.2051, 0.4803, 0.8135],
        [0.4021, 0.4529, 0.8007, 0.1441],
        [0.5034, 0.8181, 0.1690, 0.2220]])
zeros: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
ones: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
eye: tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
arange: tensor([0, 2, 4, 6, 8])
linspace: tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


Print Initialized Tensors

Printing tensors helps verify their values and structure.

In [ ]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([3, 4, 5])
print(a+b)
print(a-b)
print(a*b)
# adding using add()
print(torch.add(a,b))
print(torch.add(a, b, alpha=2))  # steps (a + bx)

tensor([4, 6, 8])
tensor([-2, -2, -2])
tensor([ 3,  8, 15])
tensor([4, 6, 8])
tensor([ 7, 10, 13])


Tensor Arithmetic Operations

Arithmetic operations on tensors are performed element-wise.

Addition: corresponding elements added.
Subtraction: corresponding elements subtracted.
Multiplication: element-wise multiplication.
torch.add(a,b) performs addition.

In [ ]:
# Element-wise multiplication (*)
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
print(f"Tensor A: {a}")
print(f"Tensor B: {b}")
print(f"Element-wise multiplication (A * B): {a * b}")
# Matrix multiplication (@)
mat_a = torch.tensor([[1, 2],
                      [3, 4]])
mat_b = torch.tensor([[5, 6],
                      [7, 8]])
print(f"\nMatrix A: {mat_a}")
print(f"Matrix B: {mat_b}")
print(f"Matrix multiplication (A @ B): {mat_a @ mat_b}")
# Example with 1D tensors (dot product)
vec_a = torch.tensor([1, 2, 3])
vec_b = torch.tensor([4, 5, 6])
print(f"\nVector A: {vec_a}")
print(f"Vector B: {vec_b}")
print(f"Dot product (Vector A @ Vector B): {vec_a @ vec_b}")

Tensor A: tensor([1, 2, 3])
Tensor B: tensor([4, 5, 6])
Element-wise multiplication (A * B): tensor([ 4, 10, 18])

Matrix A: tensor([[1, 2],
        [3, 4]])
Matrix B: tensor([[5, 6],
        [7, 8]])
Matrix multiplication (A @ B): tensor([[19, 22],
        [43, 50]])

Vector A: tensor([1, 2, 3])
Vector B: tensor([4, 5, 6])
Dot product (Vector A @ Vector B): 32


Element-wise and Matrix Multiplication

Element-wise multiplication multiplies corresponding elements.
Matrix multiplication follows linear algebra rules.

In [ ]:
t = torch.arange(1,10,1)  # numbers from 1-9 with step-size 1
print(t.reshape(3,3))  # converting t to 3x3 tensor
print(t.view(3,3))
print(t)
x = torch.tensor([[1.], [2.], [3.]])
# squeeze(): Removes dimensions of size 1 from the tensor.
print(x.squeeze())
# unsqueeze(dim): Adds a dimension of size 1 at the specified position (dim).
print(x.unsqueeze(0))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([1., 2., 3.])
tensor([[[1.],
         [2.],
         [3.]]])


Reshaping Tensors

Reshaping changes the tensor structure without changing data.

In [ ]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.tensor([7, 8, 9])
# torch.stack(): Concatenates a sequence of tensors along a new dimension.
# Here, dim=0 means a new dimension is added at the beginning, stacking t1 and t2 row-wise.
print(torch.stack([t1, t2, t3], dim=0))
print(torch.stack([t1, t2, t3], dim=1))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


Stacking Tensors

Stacking combines multiple tensors into a new tensor.

In [ ]:
t = torch.tensor([[1.,2.,3.],[4.,5.,6.]])
print(t.min(), t.max())
print(t.mean(), t.sum())
print(t.argmin(), t.argmax())  # index of min/max
# indexing (like NumPy)
print(t[0])          # first row
print(t[:, 1])       # second column
print(t[1, 2])       # single element

tensor(1.) tensor(6.)
tensor(3.5000) tensor(21.)
tensor(0) tensor(5)
tensor([1., 2., 3.])
tensor([2., 5.])
tensor(6.)


Tensor Statistics and Indexing

Statistical operations help analyze tensor data.

In [ ]:
x = torch.tensor([1, 2, 3])
print(x.dtype)                      # torch.int64 by default
f = x.type(torch.float32)
print(f.dtype)
# or specify at creation
y = torch.tensor([1.0, 2.0], dtype=torch.float16)
print(y.dtype)

torch.int64
torch.float32
torch.float16


Data Types

Tensor data types determine memory usage and precision.

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

Using device: cpu


Device Detection

Checks whether a CUDA-compatible GPU is available and selects the appropriate device.

In [ ]:
t = torch.tensor([1., 2., 3.])
t_gpu = t.to(device)
print(t_gpu.device)

cpu


Move Tensor to GPU/CPU

Moving tensors to GPU speeds up computation.

In [ ]:
# move back to CPU (needed before NumPy conversion)
t_cpu = t_gpu.cpu()
print(t_cpu.numpy())

[1. 2. 3.]
